apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Stopping an EC2 instance identified by ID.
kind: ChaosExperiment
metadata:
  name: ec2-terminate-by-id
  labels:
    name: ec2-terminate-by-id
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: 
          - "" 
          - "batch" 
          - "apps" 
          - "litmuschaos.io" 
        resources: 
          - "jobs" 
          - "pods" 
          - "pods/log" 
          - "events" 
          - "deployments" 
          - "replicasets" 
          - "pods/exec" 
          - "chaosengines" 
          - "chaosexperiments" 
          - "chaosresults" 
          - "secrets" 
          - "configmaps" 
          - "nodes" 
        verbs: 
          - "create" 
          - "list" 
          - "get" 
          - "patch" 
          - "update" 
          - "delete" 
          - "deletecollection" 
          - "get" 
          - "list" 
    image: "18000111/pyrunner:ci"
    imagePullPolicy: Always
    args:
    - -c
    - python3  experiment -name ec2-teminate-by-id
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '' 

    - name: CHAOS_INTERVAL
      value: ''

    - name: LIB
      value: 'litmus'

    - name: RAMP_TIME
      value: ''
      
    
    # enable it if the target instance is a part of self-managed nodegroup.
    - name: MANAGED_NODEGROUP
      value: 'disable'      

    # Instance ID of the target ec2 instance
    # Multiple IDs can also be provided as comma separated values ex: id1,id2
    - name: EC2_INSTANCE_ID
      value: ''

    - name: REGION
      value: ''

    - name: SEQUENCE
      value: 'parallel'

    # Provide the path of aws credentials mounted from secret  
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: '/tmp/cloud_config.yml'

    
    labels:
      name: ec2terminatebyid
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
    secrets:
    - name: cloud-secret
      mountPath: /tmp/
