apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-05-24T10:28:08Z
  name: bank-of-anthos
  version: 0.1.0
  annotations:
    categories: bank-of-anthos
    chartDescription: Injects chaos on bank-of-anthos application
spec:
  displayName: bank-of-anthos Chaos
  categoryDescription: >
    It install bank-of-anthos application, inject chaos on bank-of-anthos, uninstall the application 
    and revert the chaos
  experiments:
    - pod-delete
  keywords:
    - Kubernetes
    - bank-of-anthos
    - Pod
  platforms:
    - GKE
    - Minikube 
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: oumkale
      email: oumkale@chaosnative.com
  provider:
    name: ChaosNative
  links:
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url:
      mediatype: ""
      