apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-05-24T10:28:08Z
  name: sock-shop
  version: 0.1.0
  annotations:
    categories: sock-shop
    chartDescription: Injects chaos on sock-shop application
spec:
  displayName: sock-shop Chaos
  categoryDescription: >
    It install sock-shop application, inject chaos on sock-shop, uninstall the application 
    and revert the chaos
  experiments:
    - pod-delete
  keywords:
    - Kubernetes
    - sock-shop
    - Pod
  platforms:
    - GKE
    - Minikube 
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: oumkale
      email: oumkale@chaosnative.com
  provider:
    name: ChaosNative
  links:
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url:
      mediatype: ""
      